name: Python App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Test
      run: |
        poetry run pytest

    - name: Lint
      run: |
        poetry run black --check .

    - name: Type check
      run: |
        poetry run mypy .

    - name: Import check
      run: |
        poetry run isort --check .